language: smalltalk
os:
- linux
env:
  global:
  - PROJECT_NAME=openponk-core
  - FULL_PROJECT_NAME=$PROJECT_NAME
smalltalk:
  - Pharo64-7.0
    - PHARO_VERSION="7.0"
    - PHARO_BITS="64"
  - Pharo32-8.0
    - PHARO_VERSION="8.0"
    - PHARO_BITS="32"
  - Pharo64-8.0
    - PHARO_VERSION="8.0"
    - PHARO_BITS="64"
 # - Pharo64-9.0
 #   - PHARO_VERSION="9.0"
 #   - PHARO_BITS="64"
before_install:
  - echo $PROJECT_NAME
  - echo $FULL_PROJECT_NAME
  - echo $PHARO_BITS
  - echo $PHARO_VERSION
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BUILD_NUMBER
  - echo $SMALLTALK_CI_BUILD_BASE
  - echo $SMALLTALK_CI_HOME
  - echo $SMALLTALK_CI_BUILD
  - echo $SMALLTALK_CI_IMAGE
  - echo $SMALLTALK_CI_CHANGES
  - echo $SMALLTALK_CI_VMS
  - echo $SMALLTALK_CI_VM
deploy:
  - provider: script
    on:
      condition: $PHARO_VERSION = 8.0
    skip_cleanup: true
    script: scripts/deploy.sh
cache:
  directories:
  - "$SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache"