language: smalltalk

os:
  - linux

env:
  global:
    - ARTIFACT_DIR=openponk-image-$TRAVIS_BUILD_NUMBER
    
smalltalk:
  - Pharo64-7.0
  - Pharo32-8.0
  - Pharo64-8.0
  - Pharo64-9.0

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache
