language: smalltalk
os:
- linux
env:
  global:
  - PROJECT_NAME=openponk-core
  - FULL_PROJECT_NAME=$PROJECT_NAME
matrix:
  include:
    - smalltalk: Pharo64-7.0
      env: PHARO_VERSION="7.0" PHARO_BITS="64"
    - smalltalk: Pharo32-8.0
      env: PHARO_VERSION="8.0" PHARO_BITS="32"
    - smalltalk: Pharo64-8.0
      env: PHARO_VERSION="8.0" PHARO_BITS="64"
    - smalltalk: Pharo64-9.0
      env: PHARO_VERSION="9.0" PHARO_BITS="64"
  allow_failures:
    - smalltalk: Pharo64-7.0
      env: PHARO_VERSION="7.0" PHARO_BITS="64"
    - smalltalk: Pharo64-9.0
      env: PHARO_VERSION="9.0" PHARO_BITS="64"
before_install:
  - echo $PROJECT_NAME
  - echo $FULL_PROJECT_NAME
  - echo $PHARO_BITS
  - echo $PHARO_VERSION
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BUILD_NUMBER
  - echo $SMALLTALK_CI_BUILD_BASE
  - echo $SMALLTALK_CI_HOME
  - echo $SMALLTALK_CI_BUILD
  - echo $SMALLTALK_CI_IMAGE
  - echo $SMALLTALK_CI_CHANGES
  - echo $SMALLTALK_CI_VMS
  - echo $SMALLTALK_CI_VM
deploy:
  - provider: script
    on:
      smalltalk: Pharo64-8.0
    skip_cleanup: true
    script: 
      bash scripts/trigger_dependent.sh "class-editor" "borm-editor" "fsm-editor" "petrinets" "all-in-one"      
cache:
  directories:
  - "$SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache"
