name: Release

on:
  release:
    types: [published]
  workflow_call:

env:
  REPOSITORY_NAME: '${{ github.event.repository.name }}'
  PROJECT_NAME: 'openponk-${{ github.event.repository.name }}'
  VERSION: ${{ github.event.release.tag_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUN_ID: ${{ github.run_id }}
  
jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ github.job }}
    name: 'Test Linux'
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: hpi-swa/setup-smalltalkCI@1.3.2
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-11
      - name: Prepare image and test
        run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 12

  test-win:
    runs-on: windows-latest
    env:
      PLATFORM: ${{ github.job }}
    name: 'Test Windows'
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: hpi-swa/setup-smalltalkCI@1.3.2
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-11
      - name: Prepare image and test
        run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 20
